#!/usr/bin/env python3

from pathlib import Path
import re

# ---------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------

# Your public header
ENTRY = Path("Clockwork.h")

# Output file
OUTPUT = Path("dist/Clockwork.hpp")

# ---------------------------------------------------------------------

include_re = re.compile(r'^\s*#\s*include\s*"([^"]+)"')

visited = set()
system_includes = set()


def emit_header(file: Path, out):
    file = file.resolve()

    if file in visited:
        return

    visited.add(file)

    out.write(f"\n// ============================================================================\n")
    out.write(f"// BEGIN FILE: {file.relative_to(Path.cwd())}\n")
    out.write(f"// ============================================================================\n\n")

    for line in file.read_text(encoding="utf-8").splitlines(True):

        stripped = line.strip()

        # Ignore include guards
        if stripped == "#pragma once":
            continue

        m = include_re.match(line)
        if m:
            include_name = m.group(1)

            include_path = (file.parent / include_name).resolve()

            if include_path.exists():
                emit_header(include_path, out)
            else:
                raise FileNotFoundError(
                    f'Could not resolve include "{include_name}" '
                    f'from "{file}"'
                )

            continue

        # Keep system includes only once
        if stripped.startswith("#include <"):
            if stripped not in system_includes:
                system_includes.add(stripped)
                out.write(line)
            continue

        out.write(line)

    out.write(f"\n// END FILE: {file.relative_to(Path.cwd())}\n")


def main():
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)

    with OUTPUT.open("w", encoding="utf-8", newline="\n") as out:

        out.write("// ============================================================================\n")
        out.write("//  Clockwork.hpp\n")
        out.write("//\n")
        out.write("//  This file is automatically generated.\n")
        out.write("//  DO NOT EDIT.\n")
        out.write("// ============================================================================\n\n")

        emit_header(ENTRY, out)

    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()